### ISSUE TITLE
Can't build jar

### ISSUE THREAD

**Issue by hsiaoyi0504** [compgen-io/ngsutilsj#1]
Hi, I just download the release **0.4.2** and run `ant jar` in the root directory of the repo, but I get following error messages:
``` shell
Buildfile: /home/r04945027/ngsutilsj-ngsutilsj-0.4.2/build.xml

compile:
    [mkdir] Created dir: /home/r04945027/ngsutilsj-ngsutilsj-0.4.2/build/classes
    [javac] Compiling 205 source files to /home/r04945027/ngsutilsj-ngsutilsj-0.4.2/build/classes

BUILD FAILED
/home/r04945027/ngsutilsj-ngsutilsj-0.4.2/build.xml:35: java.lang.NullPointerException
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:157)
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:141)
        at com.sun.tools.javac.file.Locations.access$000(Locations.java:80)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:649)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:677)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.isDefault(Locations.java:566)
        at com.sun.tools.javac.file.Locations.isDefaultBootClassPath(Locations.java:115)
        at com.sun.tools.javac.util.BaseFileManager.isDefaultBootClassPath(BaseFileManager.java:137)
        at com.sun.tools.javac.main.Arguments.validate(Arguments.java:411)
        at com.sun.tools.javac.main.Main.compile(Main.java:215)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:220)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:158)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:87)
        at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:39)
        at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:36)
        at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:72)
        at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1153)
        at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:930)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 3 seconds
```

**Comment by mbreese** [comment]
Please try to pull again and rebuild. There was a missing class in the
repository that was committed locally. However, I'm not sure what the error
you're seeing is.

The current HEAD compiles on my machine, which is OSX with Oracle Java 1.8
installed.  The current target is 1.7, which might be the issue. You could
try to change '1.7' to '1.8' in the build.xml file, and that might help?
Please let me know if this works.

Marcus

--
Marcus Breese

**Comment by hsiaoyi0504** [comment]
@mbreese I can build it on my mac, but I can't build it on linux. You may want to update the release in https://github.com/compgen-io/ngsutilsj/releases page.

**Comment by hsiaoyi0504** [comment]
Can I ask a stupid question ? Why don't you upload the jar file directly into release page ? Based my understanding, the jar file should be cross-platform.

**Comment by mbreese** [comment]
That’s the plan. I was waiting until the next stable point release, but that will be in the next day or two. 

I’ll try to do the build again on Linux. But in the meantime, you can copy the `dist/ngsutilsj` file to Linux to run. That’s my main workflow for development. 

--
Marcus

**Comment by hsiaoyi0504** [comment]
@mbreese Just want let you know. I can build the jar on another linux machine. It seems that the problem is from Java 1.9 or other configuration of java environment.

**Comment by mbreese** [comment]
Good! I'm glad this was working. I just double checked that it was working on our cluster too (OpenJDK 8).
