### ISSUE TITLE
Can't filter file after samtools sort -n

### ISSUE THREAD

**Issue by chregu1971** [compgen-io/ngsutilsj#11]
Hi,
I tried to remove some read pairs from a bam file, but I get the following error when using a file that was sorted by samtools sort -n

../../../ngsutilsj/dist/ngsutilsj bam-filter --bed-exclude ../hifiasm_20230906/exclude.bed --pair-remove --silent ttt_unsort.bam ttt_exc_telo.bam
ttt_unsort.bam
ERROR: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.compgen.cmdline.MainBuilder.findAndRunInner(MainBuilder.java:692)
        at io.compgen.cmdline.MainBuilder.findAndRun(MainBuilder.java:559)
        at io.compgen.ngsutils.NGSUtils.main(NGSUtils.java:265)
Caused by: java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for /results/christian/pt_172/pt_172_001/bwa_20230907/ttt_exc_telo.bam. Sort order is queryname. Offending records are at [A02036:164:HFL2MDSX7:4:1101:1009:9972] and [A02036:164:HFL2MDSX7:4:1101:1009:10003]
        at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:186)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:176)
        at io.compgen.ngsutils.cli.bam.BamFilterCli.exec(BamFilterCli.java:602)
        ... 7 more

I do not understand why read 10003 following read 9972 is wrong.
How can I get this to work?

Best regards,
Christian

**Comment by mbreese** [comment]
This is a mismatch between samtools and htsjdk. The two programs don't actually sort reads by name the same way, which is incredibly frustrating. I'm using htsjdk to handle writing, and it forces the validation on writes.

This is more annoying than anything else. In my work, I name sort to make sure that reads all appear in one block, I don't usually care if the reads are actually sorted. 

I just pushed an update to master that adds a few options for you.

`bam-filter` now has an option `--write-unsorted`. This will force the output BAM file to be flagged as "unsorted". You should then run this through the `samtools sort -n` command to re-mark it as sorted (should be fast).

`bam-clean` has an option to strip the sorted header flag (`--reset-sorting`)

and I added `bam-sort` as a command to sort a BAM file using HTSJDK ordering.

**Comment by chregu1971** [comment]
Thank you very much for the quick fix.
/Christian
